null
[ { album:
    { album_type: 'album',
      artists: [Array],
      available_markets: [Array],
      external_urls: [Object],
      href: 'https://api.spotify.com/v1/albums/1GYVNOzwhx1nMcIJDogSNp',
      id: '1GYVNOzwhx1nMcIJDogSNp',
      images: [Array],
      name: 'Death Race For Love',
      release_date: '2019-03-08',
      release_date_precision: 'day',
      total_tracks: 22,
      type: 'album',
      uri: 'spotify:album:1GYVNOzwhx1nMcIJDogSNp' },
   artists: [ [Object] ],
   available_markets:
    [ 'AD',
      'AE',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KW',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'SA',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA' ],
   disc_number: 1,
   duration_ms: 142025,
   explicit: true,
   external_ids: { isrc: 'USUG11900401' },
   external_urls:
    { spotify: 'https://open.spotify.com/track/6eiztdXRkooWsBt2xToMWI' },
   href: 'https://api.spotify.com/v1/tracks/6eiztdXRkooWsBt2xToMWI',
   id: '6eiztdXRkooWsBt2xToMWI',
   is_local: false,
   name: 'Make Believe',
   popularity: 81,
   preview_url: null,
   track_number: 22,
   type: 'track',
   uri: 'spotify:track:6eiztdXRkooWsBt2xToMWI' },
 { album:
    { album_type: 'album',
      artists: [Array],
      available_markets: [Array],
      external_urls: [Object],
      href: 'https://api.spotify.com/v1/albums/0jZfbz0dNfDjPSg0hYJNth',
      id: '0jZfbz0dNfDjPSg0hYJNth',
      images: [Array],
      name: 'Believe',
      release_date: '1998',
      release_date_precision: 'year',
      total_tracks: 10,
      type: 'album',
      uri: 'spotify:album:0jZfbz0dNfDjPSg0hYJNth' },
   artists: [ [Object] ],
   available_markets:
    [ 'AD',
      'AE',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IS',
      'IT',
      'JO',
      'JP',
      'KW',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PT',
      'PY',
      'QA',
      'RO',
      'SA',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA' ],
   disc_number: 1,
   duration_ms: 239026,
   explicit: false,
   external_ids: { isrc: 'GBAHT9803002' },
   external_urls:
    { spotify: 'https://open.spotify.com/track/2goLsvvODILDzeeiT4dAoR' },
   href: 'https://api.spotify.com/v1/tracks/2goLsvvODILDzeeiT4dAoR',
   id: '2goLsvvODILDzeeiT4dAoR',
   is_local: false,
   name: 'Believe',
   popularity: 75,
   preview_url:
    'https://p.scdn.co/mp3-preview/579967c91dc409b693b9819c12bbba83e4d0f9a4?cid=0a9962848eeb4ab081315857f6efaa41',
   track_number: 1,
   type: 'track',
   uri: 'spotify:track:2goLsvvODILDzeeiT4dAoR' },
 { album:
    { album_type: 'album',
      artists: [Array],
      available_markets: [Array],
      external_urls: [Object],
      href: 'https://api.spotify.com/v1/albums/4D8A8M0NJjEdQhusawyeDz',
      id: '4D8A8M0NJjEdQhusawyeDz',
      images: [Array],
      name: 'Make Believe',
      release_date: '2005-05-10',
      release_date_precision: 'day',
      total_tracks: 12,
      type: 'album',
      uri: 'spotify:album:4D8A8M0NJjEdQhusawyeDz' },
   artists: [ [Object] ],
   available_markets:
    [ 'AD',
      'AE',
      'AR',
      'AT',
      'AU',
      'BE',
      'BG',
      'BH',
      'BO',
      'BR',
      'CA',
      'CH',
      'CL',
      'CO',
      'CR',
      'CY',
      'CZ',
      'DE',
      'DK',
      'DO',
      'DZ',
      'EC',
      'EE',
      'EG',
      'ES',
      'FI',
      'FR',
      'GB',
      'GR',
      'GT',
      'HK',
      'HN',
      'HU',
      'ID',
      'IE',
      'IL',
      'IN',
      'IS',
      'IT',
      'JO',
      'JP',
      'KW',
      'LB',
      'LI',
      'LT',
      'LU',
      'LV',
      'MA',
      'MC',
      'MT',
      'MX',
      'MY',
      'NI',
      'NL',
      'NO',
      'NZ',
      'OM',
      'PA',
      'PE',
      'PH',
      'PL',
      'PS',
      'PT',
      'PY',
      'QA',
      'RO',
      'SA',
      'SE',
      'SG',
      'SK',
      'SV',
      'TH',
      'TN',
      'TR',
      'TW',
      'US',
      'UY',
      'VN',
      'ZA' ],
   disc_number: 1,
   duration_ms: 196093,
   explicit: false,
   external_ids: { isrc: 'USIR10500448' },
   external_urls:
    { spotify: 'https://open.spotify.com/track/1yKu2MhpwzDXXH2tzG6xoa' },
   href: 'https://api.spotify.com/v1/tracks/1yKu2MhpwzDXXH2tzG6xoa',
   id: '1yKu2MhpwzDXXH2tzG6xoa',
   is_local: false,
   name: 'Beverly Hills',
   popularity: 68,
   preview_url: null,
   track_number: 1,
   type: 'track',
   uri: 'spotify:track:1yKu2MhpwzDXXH2tzG6xoa' } ]